export const Colors = {
  //------fixed color
  statusbarcolor: '#ffffff',
  theme_color: '#3263FD',
  theme_color2: '#8633FE',
  theme_color3:"#A689FC",
  theme_color4:"#4541C3",
  statusbar: '#ffffff',
  internetbackcolor: 'green',
  onlinebackcolor: 'green',
  internettextcolor: '#FFFFFF',
  onlinetextcolor: '#FFFFFF',
  mediabackground: '#FFFFFF',
  mediatextcolor: 'black',
  cancletextcolor: 'black',
  buttoncolor: 'red',
  whiteColor: '#FFFFFF',
  white_color: '#FFFFFF',
  greyColor: 'gray',
  Otpresedcolor: 'green',
  otpcountcolor: 'red',
  otpverifycolor: '#1985ff',
  back_color: 'FFFFFF',
  border_color: '#efefee',
  text_color: '#3a3a3a',
  text_color2: '#454545',
  black_color: '#000000',
  drawer_text_color: '#1E1E1E',
  placeholder_color: '#d4d0d6',
  edit_border_color: '#A5A5A5',
  explore_text_color: '#131313',
  res_time_color: '#B9B3B3',
  complete_color: '#88D594',
  imcomplete_color: '#C14F4F',
  redColor: 'red',
 
  //----developer color----------//

  todayColor : "#7E8385",
  letstarted : "#dadada",
  checkoutNew : "#A0A0A0",
  tabbarColor : "#F8F8F6",
  profileStatusBar : "#FEF0E5",
  progressbarBack : "#E8E7E5",
  quitChellange : "#BCBCBC",
  commentColor : "#B2B3B3",
  commentBackground : "#F7F7F7",


  // ranjit sir
  footer_bg: '#FEA057',
  input_feild : "#FCE9E1",
  // color for this app ---------------

  new_text_color:"#514EF9",
  hobby_bg:"#EBE0FF",
  greenColor:"#15760D",
  today_txt_color:'#4541C3',

  light_green: "#E5F0E4",
  ingle_color: '#6B65FF',
  border_txt_color: '#565353',
};
export const Font = {
    FontBold: 'Montserrat-Bold',
    FontBoldItalic: 'Montserrat-BoldItalic',
    FontExtraBold: 'Montserrat-ExtraBold',
    FontExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    FontExtraLightItalic: 'Montserrat-ExtraLightItalic',
    FontItalic: 'Montserrat-Italic',
    FontLight: 'Montserrat-Light',
    FontLightItalic: 'Montserrat-LightItalic',
    FontMedium: 'Montserrat-Medium',
    FontMediumItalic: 'Montserrat-MediumItalic',
    FontRegular: 'Montserrat-Regular',
    FontSemiBold: 'Montserrat-SemiBold',
    FontSemiBoldItalic: 'Montserrat-SemiBoldItalic',
    FontBlack: 'Montserrat-Black',
    FontBlackItalic: 'Montserrat-BlackItalic',
    FontExtraLight: 'Montserrat-ExtraLight',
    FontThinItalic: 'Montserrat-ThinItalic',
    FontThin: 'Montserrat-Thin',
};
