export const localimag = {
  // email: require('../Icons/email.png'),
  // password: require('../Icons/password.png'),
  // splash: require('../Icons/new_logo.png'),
  // back: require('../Icons/back.png'),
   user: require('../Icons/FooterProfileDActive.png'),
   notification: require('../Icons/notificationIcon.png'),
  resetpassword: require('../Icons/resetpassword.png'),
  terms: require('../Icons/terms.png'),
  privacy: require('../Icons/privacy.png'),
  about: require('../Icons/about.png'),
  contact: require('../Icons/contact.png'),
  rate: require('../Icons/rate.png'),
  shareapp: require('../Icons/shareapp.png'),
  // logout: require('../Icons/logout.png'),
  userplaceholder: require('../Icons/userplaceholder.png'),

  //splash
  Splash_Background: require('../Icons/Splash_Background.png'),
  welcomeScreen: require('../Icons/welcomeScreen.png'),
  welocme_logo: require('../Icons/welocme_logo.png'),
  welcomelogowhite: require('../Icons/welcomelogowhite.png'),
  MailPinkIcon: require('../Icons/MailPinkIcon.png'),
  GoogleIcon: require('../Icons/GoogleIcon.png'),
  AppleIcon: require('../Icons/AppleIcon.png'),
  email_icon: require('../Icons/email_icon.png'),
  password_icon: require('../Icons/password_icon.png'),
  blackback: require('../Icons/blackback.png'),
  dropdown_icon: require('../Icons/dropdown_icon.png'),
  country_icon: require('../Icons/country_icon.png'),
  othercountry_icon: require('../Icons/otherCountry.png'),
  birthdayCalendar: require('../Icons/birthdayCalendar.png'),
  mobileIcon: require('../Icons/mobileIcon.png'),
  GenderIcon: require('../Icons/GenderIcon.png'),
  heightIcon: require('../Icons/heightIcon.png'),
  ReligionIcon: require('../Icons/ReligionIcon.png'),
  penIcon: require('../Icons/penIcon.png'),
  OccupationIcon: require('../Icons/OccupationIcon.png'),
  downthemeIcon: require('../Icons/downthemeIcon.png'),
  addMoreFullImage: require('../Icons/addMoreFullImage.png'),
  girlImage: require('../Icons/girlImage.png'),
  HomeFlightMingleImage: require('../Icons/HomeFlightMingleImage.png'),
  ScanticketBg: require('../Icons/ScanticketBg.png'),
  ticketIcon: require('../Icons/ticketIcon.png'),
  planeIcon: require('../Icons/planeIcon.png'),
  scanwhiteIcon: require('../Icons/scanwhiteIcon.png'),
  Line: require('../Icons/Line.png'),
  SearchIcon: require('../Icons/SearchIcon.png'),
  FilterIcon: require('../Icons/FilterIcon.png'),
  UnfavouriteIcon: require('../Icons/UnfavouriteIcon.png'),
  favouriteIcon: require('../Icons/favouriteIcon.png'),
  
  favouritewithwhitebg: require('../Icons/favouritewithwhitebg.png'),
  blackBackwithwhitebg: require('../Icons/blackBackwithwhitebg.png'),
  Morewithwhitebg: require('../Icons/Morewithwhitebg.png'),
  videoCallIcon: require('../Icons/videoCallIcon.png'),
  PlusIcon: require('../Icons/PlusIcon.png'),
  pointImage: require('../Icons/pointImage.png'),

  VoiceIcon: require('../Icons/VoiceIcon.png'),
  SendIcon: require('../Icons/SendIcon.png'),
  VideoCallBG: require('../Icons/VideoCallBG.png'),
  videoPause: require('../Icons/videoPause.png'),
  videoMic: require('../Icons/videoMic.png'),
  videoCallCut: require('../Icons/videoCallCut.png'),

  EventMingle1: require('../Icons/EventMingle1.png'),
  EventMingle2: require('../Icons/EventMingle2.png'),
  PlusIconWithWhiteBg: require('../Icons/PlusIconWithWhiteBg.png'),
  RightBackThemeIcon: require('../Icons/RightBackThemeIcon.png'),
  locationMapIMage: require('../Icons/locationMapIMage.png'),

  user_edit_icon: require('../Icons/user_edit_icon.png'),
  user_settings_icon: require('../Icons/user_settings_icon.png'),
  PlusGradientIcon: require('../Icons/PlusGradientIcon.png'),
  EditGradientIcon: require('../Icons/EditGradientIcon.png'),
  GalleryGradientIcon: require('../Icons/GalleryGradientIcon.png'),
  
  Select_gallery_event: require('../Icons/Select_gallery_event.png'),
  event_type_icon: require('../Icons/event_type_icon.png'),
  location_pin: require('../Icons/location_pin.png'),
  clock_icon: require('../Icons/clock_icon.png'),
  calendar_icon: require('../Icons/calendar_icon.png'),
  updown_icon: require('../Icons/updown_icon.png'),
  searchThemeIcon: require('../Icons/searchThemeIcon.png'),
  messagecount_bg: require('../Icons/messagecount_bg.png'),
  
  TicketCardImage: require('../Icons/TicketCardImage.png'),
  ScanBG: require('../Icons/ScanBg.png'),
  HomeEventMingleImage: require('../Icons/HomeEventMingleImage.png'),
  whitebackIcon: require('../Icons/whitebackIcon.png'),
  FooterHomeDActive:require('../Icons/FooterHomeDActive.png'),
  FooterHomeActive:require('../Icons/FooterHomeActive.png'),
  FooterMessagesDActive:require('../Icons/FooterMessagesDActive.png'),
  FooterMessagesActive:require('../Icons/FooterMessagesActive.png'),
  FooterFavouriteDActive:require('../Icons/FooterFavouriteDActive.png'),
  FooterFavouriteActive:require('../Icons/FooterFavouriteActive.png'),
  FooterProfileDActive:require('../Icons/FooterProfileDActive.png'),
  FooterProfileActive:require('../Icons/FooterProfileActive.png'),


  INGLE_logo: require('../Icons/INGLE.png'),
  iPhone13mini: require('../Icons/iPhone13mini.png'),
  Group_border: require('../Icons/Group_border.png'),


  termsconditionIcon : require("../Icons/icon_termscondition.png"),
  privacypolicyIcon : require("../Icons/icon_privacypolicy.png"),
  aboutusIcon : require("../Icons/icon_aboutus.png"),
  subscriptionsIcon : require("../Icons/icon_subscriptions.png"),
  contactusIcon : require("../Icons/icon_contactus.png"),
  languageIcon : require("../Icons/icon_language.png"),
  changepasswordIcon : require("../Icons/icon_changepassword.png"),
  rateappIcon : require("../Icons/icon_rateapp.png"),
  shareappIcon : require("../Icons/icon_shareapp.png"),
  deleteaccountIcon : require("../Icons/icon_deleteaccount.png"),
  logoutIcon : require("../Icons/icon_logout.png"),
  rightIcon : require("../Icons/icon_right.png"),

};
